### ISSUE TITLE
確認メッセージが表示されません

### ISSUE THREAD

**Issue by matyuda** [smt7174/20240608-jawsug-kanazawa-cdk-workshop#3]
以下の手順にある確認メッセージがWindows 11の環境では表示されません。表示される条件はありますか？
https://github.com/smt7174/20240608-jawsug-kanazawa-cdk-workshop/blob/main/README.md?plain=1#L153

なお、実行完了すると
https://github.com/smt7174/20240608-jawsug-kanazawa-cdk-workshop/blob/main/README.md?plain=1#L162
のフォルダの通りにファイル等が作成されていることは確認できました。

```
c:\work\20240608-jawsug-kanazawa-cdk-workshop\jawsug-kanazawa-cdk>npx cdk init app --language typescript
Applying project template app for typescript
# Welcome to your CDK TypeScript project

This is a blank project for CDK development with TypeScript.

The `cdk.json` file tells the CDK Toolkit how to execute your app.

## Useful commands

* `npm run build`   compile typescript to js
* `npm run watch`   watch for changes and compile
* `npm run test`    perform the jest unit tests
* `npx cdk deploy`  deploy this stack to your default AWS account/region
* `npx cdk diff`    compare deployed stack with current state
* `npx cdk synth`   emits the synthesized CloudFormation template

Executing npm install...
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
✅ All done!
```

**Comment by smt7174** [comment]
> 以下の手順にある確認メッセージがWindows 11の環境では表示されません。表示される条件はありますか？
  
一応、 ```--force``` オプションをつけたり ```--require-approval``` オプションで ```never``` を設定するとメッセージが非表示となりますが、それは未設定ですよね？  
上記以外に、メッセージの表示条件はありません。(デフォルトが「表示される」設定)
  
現時点ではWindows11の環境で試していないので何とも言えません。環境が準備できたら試してみます。(私はWindows10に環境作成したWSL2(Ubuntu)で動作確認しました。)

**Comment by smt7174** [comment]
あと可能性があるとすれば、すでに該当バージョンのCDKがグローバルインストールなどがされている、などです。  
  
なおこのメッセージは、該当バージョンのCDKがインストールされていない場合のみ表示されるので、表示されない場合はそれで問題ありません

**Comment by matyuda** [comment]
ありがとうございます。

> 該当バージョンのCDKがグローバルインストールなどがされている

に該当していました。

> c:\work\20240608-jawsug-kanazawa-cdk-workshop\jawsug-kanazawa-cdk>npm list -g
> C:\Users\yasuh\AppData\Roaming\npm
> +-- aws-cdk@2.142.1
> `-- wrangler@3.0.0
